################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: filtered-emea-orders-gitops
  namespace: event-automation
spec:
  mode: native
  taskManager:
    resource:
      cpu: 2
      memory: 4096m
  jobManager:
    replicas: 1
    resource:
      cpu: 0.5
      memory: 4096m
  flinkConfiguration:
    license.accept: 'true'
    license.license: L-HRZF-DWHH7A
    license.use: EventAutomationProduction
    state.checkpoints.dir: 'file:///opt/flink/volume/flink-cp'
    state.checkpoints.num-retained: '3'
    state.savepoints.dir: 'file:///opt/flink/volume/flink-sp'
  serviceAccount: flink
  flinkVersion: v1_18
  image: 'quay.io/raphael_tholl/filtered-emea-orders:1.0'
  job:
    allowNonRestoredState: true
    args:
      - /opt/flink/usrlib/sql-scripts/simple.sql
    jarURI: 'local:///opt/flink/usrlib/sql-runner.jar'
    parallelism: 1
    state: running
    upgradeMode: savepoint
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: type
                      operator: In
                      values:
                        - flink-native-kubernetes
                topologyKey: kubernetes.io/hostname
              weight: 80
      containers:
        - name: flink-main-container
          volumeMounts:
            - mountPath: /opt/flink/log
              name: flink-logs
            - mountPath: /opt/flink/usrlib/sql-scripts/
              name: cm-sql
            - mountPath: /opt/flink/volume/
              name: state
      volumes:
        - name: state
          persistentVolumeClaim: 
            claimName: flink-vol
        - name: cm-sql
          configMap: 
            name: cm-sql
        - name: flink-logs
          emptyDir: {}